# Generated by Django 5.0 on 2023-12-26 02:49

import albums_singles.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "album_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор альбома",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=50, verbose_name="Название альбома"
                    ),
                ),
                (
                    "release_year",
                    models.IntegerField(verbose_name="Год выпуска альбома"),
                ),
                (
                    "cover",
                    models.ImageField(
                        default="albums/img/0_img_album.png",
                        upload_to=albums_singles.models.album_cover_path,
                        verbose_name="Обложка альбома",
                    ),
                ),
                (
                    "tracks",
                    models.ManyToManyField(related_name="albums", to="tracks.track"),
                ),
            ],
            options={
                "verbose_name": "Альбом",
                "verbose_name_plural": "Альбомы",
            },
        ),
        migrations.CreateModel(
            name="Single",
            fields=[
                (
                    "single_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор сингла",
                    ),
                ),
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="singles",
                        to="tracks.track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сингл",
                "verbose_name_plural": "Синглы",
            },
        ),
    ]
