# Generated by Django 5.0 on 2023-12-26 03:04

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_photo",
            field=models.ImageField(
                default="users/img/0_img_user.png",
                upload_to=users.models.user_photo_path,
                verbose_name="Фото пользователя",
            ),
        ),
    ]
