# Generated by Django 5.0 on 2023-12-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                default="",
                max_length=254,
                unique=True,
                verbose_name="Адрес электронной почты",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(default="", max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(default="", max_length=30, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default="", max_length=150, unique=True, verbose_name="Никнэйм"
            ),
        ),
    ]
