# Generated by Django 5.0 on 2023-12-26 02:49

import django.core.validators
import tracks.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("singers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "track_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор трека",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=50, verbose_name="Название трека"
                    ),
                ),
                ("release_year", models.IntegerField(verbose_name="Год выпуска трека")),
                (
                    "cover",
                    models.ImageField(
                        default="tracks/img/0_img_track.png",
                        upload_to=tracks.models.track_photo_path,
                        verbose_name="Обложка трека",
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        upload_to=tracks.models.track_audio_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3", "wav", "ogg", "flac", "mp4"]
                            )
                        ],
                        verbose_name="Аудио запись трека",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(related_name="tracks", to="singers.genre"),
                ),
                (
                    "singers",
                    models.ManyToManyField(related_name="tracks", to="singers.singer"),
                ),
            ],
            options={
                "verbose_name": "Трек",
                "verbose_name_plural": "Треки",
            },
        ),
    ]
